language: android

jdk: oraclejdk8
		
 before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - node_modules
    - $HOME/.gradle/caches/

sudo: false

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

   licenses:
    - 'android-sdk-license-.+'

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8   

before_install:
  # Grand gradlew proper rights to operate 
  - chmod +x gradlew

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - echo $ADB_INSTALL_TIMEOUT
  - android list target
  - ./gradlew connectedAndroidTest

notifications:
  email:
    - sjoerd+test-continuous@afrogleap.com

#before_install:
#install:
#before_script:
#script:
#after_success or after_failure:
#after_script:
#OPTIONAL before_deploy:
#OPTIONAL deploy:
#OPTIONAL after_deploy: 
