language: android

jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - node_modules
    - $HOME/.gradle/caches/

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_install:
  # Grand gradlew proper rights to operate
  - chmod +x gradlew

install:
   - ./gradlew --version # show version and download Gradle Wrapper when is not present in cache
   - ./execute create-and-start-device wait-for-device-online
  
before_script:
  - ./gradlew test #run unit tests

script:
  # - android list target
  - ./gradlew connectedAndroidTest

notifications:
  email:
    - sjoerd+test-continuous@afrogleap.com

#before_install:
#install:
#before_script:
#script:
#after_success or after_failure:
#after_script:
#OPTIONAL before_deploy:
#OPTIONAL deploy:
#OPTIONAL after_deploy: 
