language: java

env:
  - TERM=dumb

before_install:
 - chmod +x gradlew

script:
  - ./gradlew assemble -x test

#before_install:
#install:
#before_script:
#script:
#after_success or after_failure:
#after_script:
#OPTIONAL before_deploy:
#OPTIONAL deploy:
#OPTIONAL after_deploy: