language: android

jdk: oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_install:
  # Grand gradlew proper rights to operate 
  - chmod +x gradlew

# Emulator Management: Create, Start and Wait 
before_script:
 - echo no | android create avd --force -n test -t android-19 --sdcard 10M --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &
  
# script: # ./gradlew :app:connectedCheck  

notifications:
  email:
    - sjoerd+test-continuous@afrogleap.com

#before_install:
#install:
#before_script:
#script:
#after_success or after_failure:
#after_script:
#OPTIONAL before_deploy:
#OPTIONAL deploy:
#OPTIONAL after_deploy: 
